language: node_js
node_js:
  - "lts/*"

services:
  - docker

install:
  - npm install
  - npm run-script build

after_success:
  - docker build -t achorein/ultimateplateform-phaser .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push achorein/ultimateplateform-phaser

deploy:
  provider: firebase
  token:
    secure: "$FIREBASE_TOKEN"
  project: "utlimate-plateform"
  skip_cleanup: true
  on:
    branch: master
